version: "2.1"

services:

  coturn:
    container_name: coturn
    image: coturn:$VERSION_COTURN
    build: "https://git.scimetis.net/yohan/docker-coturn.git"
    restart: unless-stopped
    network_mode: "host"
    command: ["--listening-port", "3478", "--verbose", "--fingerprint", "--use-auth-secret", "--static-auth-secret", "$SECRET", "--realm", "scimetis.net", "--total-quota", "100", "--bps-capacity", "0", "--stale-nonce", "--no-multicast-peers"]
    expose: 
      - "3478"
